apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.backend.environment | quote }}
  PORT: {{ .Values.backend.port | quote }}
  DB_HOST: {{ .Values.backend.database.host | quote }}
  DB_PORT: {{ .Values.backend.database.port | quote }}
  DB_NAME: {{ .Values.backend.database.name | quote }}
  DB_USER: {{ .Values.backend.database.username | quote }}
